<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html lang="pl">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Darmowa platforma do zarządzania domowym budżetem</title>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/cash.icon', 'href' => $this->basePath() . '/images/cash.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
</head>

<body>
<div id="templatemo_container">
	<div id="templatemo_leftcolumn">
		<div id="templatemo_sitetitle">
			<div class="title">Budżet Domowy</div>
	        <div class="tagline">Wersja 0.1</div>
	    </div>

	    <div id="templatemo_menu">
	    	<div class="templatemo_menu_top"></div>
	        <ul>
	          	<li><a href="<?php echo $this->url('home') ?>">Strona domowa</a></li>
				<li><a href="<?php echo $this->url('kontakt') ?>">Kontakt</a></li>
	        </ul>
	      <div class="templatemo_menu_bottom"></div>
	    </div>

	    <div id="templatemo_search">
		    <h2>Logowanie</h2>
	        <form method="post" action="#">
	          <div class="form_row">
	          	<label><strong>Email</strong></label><input name="username" type="text" class="inputfield" placeholder="email.." id="email_addremss" maxlength="30"/>
	          </div>
	          <div class="form_row">
	          	<label><strong>Hasło</strong></label><input name="password" type="password" class="inputfield" placeholder="hasło.." id="password" maxlength="30"/>
	          </div>
	          <input class="button" type="submit" name="Submit" value="Login" />
	        </form>
	    </div>

	    <div class="leftcolumnsection">
	<a href="http://validator.w3.org/check?uri=referer"><img style="border:0;width:88px;height:31px" src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" width="88" height="31" vspace="8" border="0" /></a>
	<a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px"  src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" vspace="8" border="0" /></a>
		</div>

	</div>

	<div id="templatemo_rightcolumn">

	   <div id="templatemo_one_column">
		<?php echo $this->content; ?>
		</div>

	   <div id="templatemo_footer">
	      <a href="<?php echo $this->url('home') ?>">Strona domowa</a> | <a href="<?php echo $this->url('kontakt') ?>">Kontakt</a><br>
	         Wykonali: Broda Samo Zło i Wujek Google
	   </div>
	</div>
</div>
</body>
</html>